### ISSUE TITLE
Compilation issue

### ISSUE THREAD

**Issue by obiwankennedy** [eeertekin/bbcp#1]
I'm trying to compile bbcp but I'm running into issue: 

make[1]: Entering directory `/media/bigone/work/application/bbcp-master/src'
make[2]: Entering directory`/media/bigone/work/application/bbcp-master/src'
make[2]: **\* No rule to make target `makeLinuxunknown'.  Stop.
make[2]: Leaving directory`/media/bigone/work/application/bbcp-master/src'
make[1]: **\* [Linux] Error 2
make[1]: Leaving directory `/media/bigone/work/application/bbcp-master/src'
make: **\* [all] Error 2

I tried to compile as normal user or root, got same results.
I guess the code trying to detect my linux version is failing. 

Do you have some tips ?

**Comment by WagnerGMD** [comment]
I met this issue and yes there's a little tips. For me, the solution was to edit the makefile (inside the folder src).
At the line 194, replace the parameter i by m. Look [here](https://github.com/WagnerGMD/bbcp/commit/d9444b469eee781cc0ccff9c9444b428ad606f59), if you need more details.
Before any new attempt, my advice would be to check the result. Simply try the command : "uname -m".

**Comment by obiwankennedy** [comment]
Yes, I found the same tips, but source change will be better.

**Comment by eeertekin** [comment]
@obiwankennedy 

What is your distro ?

**Comment by obiwankennedy** [comment]
Debian or/and Ubuntu

**Comment by eeertekin** [comment]
Machine name will be used instead of platform, it should be fine on master branch.

Thanks!
