### ISSUE TITLE
Owner is not preserved

### ISSUE THREAD

**Issue by rareshornet** [eeertekin/bbcp#3]
Hi there and then you for bbcp first of all. Saves us a great hasle bybusing bbcp over hi latency wan connections. We have an interesting issue. Aparently ownership is not preserved by bbcp. we are using bbcp with -p and compres flags. Is there a something else that we are missing?

Thanks!

**Comment by rareshornet** [comment]
sorry for bad writing, im.writing from my phone and im freeezing :P

**Comment by mkll** [comment]
@rareshornet You are freezing? Are you ok? Should we call 911 to save you from freezing?

**Comment by rareshornet** [comment]
ain't you a really nice d**\* :D mkll
